### PR TITLE
Proposed changes for account security, Python 3 compatibility

### PR DESCRIPTION
**Pull request by cedricgc**
I moved many of the settings into a json file that is read into a dictionary at runtime. Please copy settings.json.skel into settings.json and fill in the values for username/password. Also, please change the accounts' password as just about anybody can hijack it right now. Remember to put the settings.json in your gitignore file so it is not pushed to Github.

I also changed some syntax (String formatting, Exceptions, wrapping in main) for Python 3 compatibility  and to follow best practices.

### CODE REVIEW

**Comment by bag-man** [comment]
Ah cool thanks for contributing :) I hadn't considered making it Python 3
compatible, what advantages does that bring?

As for the password security, I made a decision not to include a settings
file and just hardcode a false password in to the main script, as even with
a settings file you will need to either add that to the .gitignore and
recreate it on each new system, or change the password in the settings file
anyway. So just hardcoding it in the main script keeps it really simple and
keeps the project in one simple file; it isn't like this is going to be ran
on multiple servers / accounts anyway.

**Comment by cedricgc** [comment]
Oh okay if its not the real password it should be fine. I think in terms of usability have a configuration file is better but I will leave it to you. I am glad I looked through the code, I think I could use selenium in testing my own websites :)

**Comment by bag-man** [comment]
I would add a config file if it is ever intended to be used in more than
one instance. If you use Selenium don't bother using Firefox, PhantomJS is
much more stable and requires a lot less resources.

**Comment by bag-man** [comment]
It would be great to make this a more flexible framework so it could be adapted for other sites more easily. I'm closing this for now, thanks for your thoughts.

**Pull request closed without merging**
