### PR TITLE
Gave dm_bot a new host

### PR DESCRIPTION
**Pull request by esn89**
Since a.pomf.se is not longer with us, I haven't seen dm_bot in action in awhile.  I gave it a new host and hopefully this gets him up and running in no time.

### CODE REVIEW

**Comment by bag-man** [comment]
Awesome, sad to hear about pomf.se I'm away for a month so do you want to
run dmbot till I get back? I can get the password for you

**Comment by esn89** [comment]
I would love to.  I have quite a bit of spare time this summer, I can keep it running.

**Comment by bag-man** [comment]
Awesome, the password is 1q2w3e4r. I will kill my instance, see if you can
make it more stable :)

Thanks a lot,

Owen

**Comment by esn89** [comment]
No worries. Gonna see if I can get him up and running by tomorrow afternoon, after I get the dependencies installed. 

By the way, I assume that you set this script as a cron job? If so, what's the time interval between each running of the script?

**Comment by vyp** [comment]
Just fyi guys, the password is publicly visible on github, and it's definitely already been seen/harvested. (There are bots that listen in on the some public github event api or something, and just continually harvest everything that looks like passwords/keys etc.) So definitely do change it asap if not done so already, no matter how small or unpopular you think dm_bot is. (I'm assuming the password being up here is not a good thing, no matter how generic it is?)

**Comment by bag-man** [comment]
Shit I forgot this was a public mailing list.

I'll change it now, email me direct for the key.

**Comment by bag-man** [comment]
Scrap that, someone else change it, u haven't got time, email me the
password please :)

**Comment by esn89** [comment]
Did someone else change it already? I went to sleep shortly after I sent
you the email about a cron job.

Regards.

Evan

**Comment by vyp** [comment]
I didn't do anything by the way. :|

**Comment by esn89** [comment]
Ah, so the password has been changed by someone else?

**Comment by vyp** [comment]
Well I don't know, did you try accessing it? (Like I don't even know where the bot is, and if you do know, obviously don't say it here.)

**Comment by vyp** [comment]
Also, this might be a problem: http://img.loveisover.me/

> Goodbye.
> 
> When Pomf closed its doors, we received an influx of traffic that my server bandwidth was unable to sustain. So unfortunately, effective immediately, I am closing the doors of LiO Image Hosting. I could upgrade the server, throttle the image hosting, or auto-prune images, but I feel that wouldn't make me or you guys happy, so its probably best just to close my doors so you guys can go find something better for now. Thanks for all your support these last couple of years and I hope we will see each other again.
> 
> \- Blade

**Comment by vyp** [comment]
FFS, that was the reddit account password you mean! I just figured it out and changed it! Just in case!

**Comment by vyp** [comment]
I will email you guys the new password.

**Comment by bag-man** [comment]
Cheers man, looks like we need to find a new host :/

**Comment by esn89** [comment]
Hey sorry give me a sec. Just cooking some breakfast right now.

**Comment by bag-man** [comment]
Not urgent, I'm in a little town in Sweden for a month doing construction
all day so I don't have much time. I can connect to my server to run stuff
if you need somewhere to test with all the dependencies installed.

**Comment by esn89** [comment]
Alright, it's great that we got the password for the dmbot figured out.  

At the moment, I am going to look for a new image host and hopefully I can send a pull request soon.

If you are busy with construction, I can also run dmbot on my server as well, so that I don't have to keep bombarding you with emails/requests.

**Comment by bag-man** [comment]
Yeah that is fine but me. Always good to spread out the hosting in case the
DM notices!

**Comment by esn89** [comment]
alright, my pull request is updated with a new host.  let me know if you see it and you can merge if you want.

**Comment by bag-man** [comment]
Cool, I will try and take a look tonight if I have some spare time. Thanks
a lot for helping on this project!

**Comment by esn89** [comment]
No worries.  Let me know and I can fire up an instance of dm_bot on my server

**Comment by esn89** [comment]
Would you want me to run an instance of it on my server, or will you be doing that?

**Comment by bag-man** [comment]
If you could that would be awesome. We were having stability issues on my
shitty VPS, maybe better specs would help.

Thanks

**Comment by esn89** [comment]
will do that.  probably sometime tonight.  

Do you have any preferences? I am thinking of making it as a cronjob.  Was that what you did?  if so, how long was the interval?

**Comment by bag-man** [comment]
Just run the script in a screen/tmux session or use nohup. It should run by
itself no scheduling needed

**Comment by esn89** [comment]
sounds good.  i think i'll do that then.

**Comment by esn89** [comment]
gonna work on this a bit more tonight, i think they changed their api in terms of authentication processes, and when I ran dmbot on my server, I got this:

http://i.imgur.com/LGG5TbY.png

maybe i'll open a new PR when i'm done.   Btw this is on a debian testing server.

**Comment by bag-man** [comment]
Finally I am back in reality, with a keyboard and mouse!

Where did we get to on this?

**Comment by esn89** [comment]
Hey, 

For this, we got to finding your bot a new image host.  However, I tried hosting it on my Debian server  (stable) and kept getting those errors that I showed you from two posts above.

Weird thing is that, the dmbot.py runs fine on my laptop, but being that it's my laptop I can't host it there.
I have a banana-pi coming in and I am planning on testing it there in the next month.
Also:  I think sometime in August, the login feature with user/pass will be deprecated in the new PRAW, so we gotta work on that.

**Comment by vyp** [comment]
What does your laptop run? Or does it also run debian stable?

**Comment by vyp** [comment]
>  Also: I think sometime in August, the login feature with user/pass will be deprecated in the new PRAW, so we gotta work on that.

Yes I think this is correct. Here's the link as you have in your screenshot: https://www.reddit.com/comments/2ujhkr

**Comment by esn89** [comment]
@vyp  my laptop runs debian testing

**Comment by vyp** [comment]
@esn89 So you've confirmed it's not because of different python versions?

**Comment by esn89** [comment]
@vyp it isn't because of different python versions.  I did everything I could in my power to ensure that all the packages' versions on my VPS matched the ones on my laptop.

Since some changes will be made to the API on August the 3rd, how about we tinker around after August the 3rd?  

By that time I would have flown home and have access to my desktop, and the new PRAW is out.

**Comment by vyp** [comment]
@esn89 Sounds good. :+1:

**Comment by bag-man** [comment]
I thought we had an issue with the image host, but I just checked and they are still up. Should I just run the latest version on my server? Probably easiest.

Tried running it, but got this: 

We got one! http://redd.it/3es4xt
Failed to submit:
('Connection aborted.', BadStatusLine("''",))

**Comment by esn89** [comment]
Nope, the issue with image hosting was fixed with this pull request that you closed.  The issue for me after that was running it on my VPS.  You could give it a shot.

edit:  just saw your "Failed to submit" message, I will try it on my laptop tonight.

**Pull request merged**
